name: CI

on: [push]

jobs:
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json

 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Log into Docker Hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKER_USER }}
      password: ${{ secrets.DOCKER_PAT }}

   - name: Set up Docker
     uses: docker/setup-buildx-action@v3

   - name: Build Docker Image
     uses: docker/build-push-action@v4
     with:
       context: .
       load: true
       tags: myapp:latest
       sbom: false
       provenance: false

   - name: Docker Scout Scan
     uses: docker/scout-action@v1
     with:
       command: quickview,cves
       image: myapp:latest
